title: Data Science Portfolio
description: Quantile Regression Analysis of Insurance Charges
baseurl: ""
url: "https://saisri27.github.io/linearregressionproject"
author: Sai Sri Maddirala

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Navigation
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: About
    url: /about

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Exclude files
exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - app.py
  - requirements.txt
  - start.sh
  - *.ipynb
