title: Quantile Regression Analysis
description: Quantile Regression Analysis of Insurance Charges
baseurl: ""
url: "https://saisri27.github.io/qranalysis"
author: Sai Sri Maddirala

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Math rendering
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Include files that Jekyll normally excludes
include:
  - plots/

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Exclude files
exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - app.py
  - requirements.txt
  - start.sh
  - "*.ipynb"
